<a href="https://colab.research.google.com/github/Ajaykumar-02/Deep-Learning/blob/main/Basic_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:

# Dummy Data Create
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
#Normalization
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8, activation = 'relu'), #Hidden layer
    layers.Dense(1, activation='sigmoid') #Output Layer
])

In [ ]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4 , verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 152ms/step - accuracy: 0.6667 - loss: 0.7760 - val_accuracy: 0.5000 - val_loss: 4.9155
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 3.7626 - val_accuracy: 0.7500 - val_loss: 0.7582
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4167 - loss: 5.1428 - val_accuracy: 0.5000 - val_loss: 0.7284
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.9120 - val_accuracy: 0.7500 - val_loss: 1.0153
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 2.3301 - val_accuracy: 0.5000 - val_loss: 1.2857
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.7473 - val_accuracy: 0.5000 - val_loss: 2.2565
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 2.5789 - val_accuracy: 0.7500 - val_loss: 0.7144
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 1.8149 - val_accuracy: 0.5000 - val_loss: 3.0076
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 2.3941 - val_accuracy: 0.7500 - val_loss: 0.7533
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 1.6503 - val_accuracy: 0.5000 - val_loss: 2.4858
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.8760 - val_accuracy: 0.5000 - val_loss: 1.2550
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4167 - loss: 0.8620 - val_accuracy: 0.5000 - val_loss: 3.2901
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5833 - loss: 1.2473 - val_accuracy: 0.5000 - val_loss: 1.3456
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1667 - loss: 4.6020 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5833 - loss: 0.7850 - val_accuracy: 0.2500 - val_loss: 0.7202
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 1.4496 - val_accuracy: 0.5000 - val_loss: 1.8739
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.7837 - val_accuracy: 0.7500 - val_loss: 0.8559
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4167 - loss: 1.0290 - val_accuracy: 0.5000 - val_loss: 1.7264
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6667 - loss: 0.7922 - val_accuracy: 0.5000 - val_loss: 1.6318
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4167 - loss: 1.6946 - val_accuracy: 0.5000 - val_loss: 0.6506
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 1.1584 - val_accuracy: 0.5000 - val_loss: 0.9305
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4167 - loss: 1.0843 - val_accuracy: 0.5000 - val_loss: 1.1540
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.7093 - val_accuracy: 0.5000 - val_loss: 0.9369
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.8505 - val_accuracy: 0.7500 - val_loss: 0.6464
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7814 - val_accuracy: 0.5000 - val_loss: 1.2567
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4167 - loss: 1.1427 - val_accuracy: 0.5000 - val_loss: 0.6565
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.6855 - val_accuracy: 0.5000 - val_loss: 1.4361
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 1.0951 - val_accuracy: 0.5000 - val_loss: 2.5094
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3333 - loss: 1.8877 - val_accuracy: 0.5000 - val_loss: 1.4014
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3333 - loss: 1.4439 - val_accuracy: 0.7500 - val_loss: 0.7585
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3333 - loss: 1.0262 - val_accuracy: 0.5000 - val_loss: 1.6179
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.9151 - val_accuracy: 0.5000 - val_loss: 0.9024
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 1.0264 - val_accuracy: 0.5000 - val_loss: 1.6949
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.8752 - val_accuracy: 0.5000 - val_loss: 0.8188
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 1.0281 - val_accuracy: 0.5000 - val_loss: 0.8650
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3333 - loss: 1.0617 - val_accuracy: 0.5000 - val_loss: 1.1622
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6520 - val_accuracy: 0.5000 - val_loss: 0.6365
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.1667 - loss: 1.6635 - val_accuracy: 0.5000 - val_loss: 0.7946
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 1.3397 - val_accuracy: 0.5000 - val_loss: 0.6352
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3333 - loss: 1.0786 - val_accuracy: 0.7500 - val_loss: 0.7069
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6742 - val_accuracy: 0.5000 - val_loss: 0.7734
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6970 - val_accuracy: 0.7500 - val_loss: 0.6618
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6898 - val_accuracy: 0.5000 - val_loss: 0.8021
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6761 - val_accuracy: 0.5000 - val_loss: 0.7755
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6679 - val_accuracy: 0.5000 - val_loss: 0.7324
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3333 - loss: 1.2339 - val_accuracy: 0.7500 - val_loss: 0.6731
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.6788 - val_accuracy: 0.5000 - val_loss: 0.8482
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.7528 - val_accuracy: 0.7500 - val_loss: 0.6741
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7024 - val_accuracy: 0.7500 - val_loss: 0.6962
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7387 - val_accuracy: 0.5000 - val_loss: 0.8193
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.9030 - val_accuracy: 0.5000 - val_loss: 0.6468
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.7487 - val_accuracy: 0.5000 - val_loss: 0.7787
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7436 - val_accuracy: 0.7500 - val_loss: 0.6669
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6982 - val_accuracy: 0.5000 - val_loss: 0.7202
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7374 - val_accuracy: 0.5000 - val_loss: 0.7349
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6999 - val_accuracy: 0.7500 - val_loss: 0.6691
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4167 - loss: 0.8569 - val_accuracy: 0.5000 - val_loss: 0.9900
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.7797 - val_accuracy: 0.5000 - val_loss: 0.8213
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6857 - val_accuracy: 0.5000 - val_loss: 0.7510
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7357 - val_accuracy: 0.7500 - val_loss: 0.6683
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4167 - loss: 0.7507 - val_accuracy: 0.7500 - val_loss: 0.6693
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.7442 - val_accuracy: 0.5000 - val_loss: 0.7300
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7329 - val_accuracy: 0.7500 - val_loss: 0.6693
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7954 - val_accuracy: 0.5000 - val_loss: 0.7989
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6743 - val_accuracy: 0.5000 - val_loss: 0.7146
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4167 - loss: 0.6863 - val_accuracy: 0.5000 - val_loss: 0.7547
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6948 - val_accuracy: 0.7500 - val_loss: 0.6924
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4167 - loss: 0.7622 - val_accuracy: 0.5000 - val_loss: 0.7396
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6681 - val_accuracy: 0.5000 - val_loss: 0.7224
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3333 - loss: 0.7312 - val_accuracy: 0.5000 - val_loss: 0.7500
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6942 - val_accuracy: 0.7500 - val_loss: 0.6956
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.7168 - val_accuracy: 0.5000 - val_loss: 0.7247
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6708 - val_accuracy: 0.5000 - val_loss: 0.7399
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6680 - val_accuracy: 0.5000 - val_loss: 0.7131
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7116 - val_accuracy: 0.7500 - val_loss: 0.6737
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6846 - val_accuracy: 0.5000 - val_loss: 0.7073
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2500 - loss: 0.8543 - val_accuracy: 0.5000 - val_loss: 0.7805
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4167 - loss: 0.8112 - val_accuracy: 0.5000 - val_loss: 0.7943
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.8534 - val_accuracy: 0.7500 - val_loss: 0.6954
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.8386 - val_accuracy: 0.5000 - val_loss: 0.7292
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4167 - loss: 0.7140 - val_accuracy: 0.5000 - val_loss: 0.7279
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.8186 - val_accuracy: 0.5000 - val_loss: 0.7379
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6984 - val_accuracy: 0.5000 - val_loss: 0.7046
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.7024 - val_accuracy: 0.5000 - val_loss: 0.7080
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6964 - val_accuracy: 0.5000 - val_loss: 0.7221
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.6686 - val_accuracy: 0.5000 - val_loss: 0.7186
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.8371 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7434 - val_accuracy: 0.5000 - val_loss: 0.7393
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.6735 - val_accuracy: 0.5000 - val_loss: 0.7230
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3333 - loss: 0.7503 - val_accuracy: 0.5000 - val_loss: 0.7239
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6826 - val_accuracy: 0.7500 - val_loss: 0.6995
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.7564 - val_accuracy: 0.5000 - val_loss: 0.7458
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.6927 - val_accuracy: 0.5000 - val_loss: 0.7039
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.6818 - val_accuracy: 0.7500 - val_loss: 0.6969
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4167 - loss: 0.7216 - val_accuracy: 0.7500 - val_loss: 0.6971
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4167 - loss: 0.7051 - val_accuracy: 0.7500 - val_loss: 0.6938
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4167 - loss: 0.7123 - val_accuracy: 0.7500 - val_loss: 0.6974
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6895 - val_accuracy: 0.5000 - val_loss: 0.7064
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.6894 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5833 - loss: 0.6715 - val_accuracy: 0.5000 - val_loss: 0.7145